### ISSUE TITLE
Could not set team ID to 'xxxxxxxxxx', only found the following available teams: 118361725, 118103445, 118225401, 118456689

### ISSUE THREAD

**Issue by singhamit089** [bitrise-io/build.issues#10]
While uploading the build to iTunes Connect with "Deploy to iTunes Connect / TestFlight (with Deliver)" There seems to be problem with it detecting my team_id

Even tough I have provided the team_id it couldn't find it.

Where did the issue happen? -> Deploy to iTunes Connect / TestFlight (with Deliver)

**Comment by viktorbenei** [comment]
The error `Could not set team ID to 'xxxxxxxxxx', only found the following available teams` seems to come from `deliver` and not from our Step - can you please create an issue on their GitHub page? https://github.com/fastlane/fastlane/tree/master/deliver

**Comment by singhamit089** [comment]
@viktorbenei I have raised a issue with fastlane as suggested by you. Here is the [link](https://github.com/fastlane/fastlane/issues/7142#issuecomment-262446060) of the same. But I am being asked for the fast-file, the thing is I have not created one and I never had to create one before.

**Comment by viktorbenei** [comment]
Can you please send us the full build log? We'll highlight the deliver command used, that should be enough for them

**Comment by singhamit089** [comment]
@viktorbenei just did.

**Comment by viktorbenei** [comment]
In the log I saw that you specified both the Team ID and the Team Name - can you please remove the Team ID (just delete the value of the input) and only specify the Team Name?

My guess based on the log is that `deliver` might require some kind of internal team ID - if you check the error, the Developer Team ID you specified is alpha numerical (e.g. `12345A12B1`), while the IDs deliver lists as "available" team IDs include only numbers, and are 1 character shorter too (e.g. `123456789`).

Relevant part of the log (with changed value):

```
Could not set team ID to '12345A12B1', only found the following available teams: 123456789, 223456789, 323456789, 423456789
```

**Comment by viktorbenei** [comment]
Related fastlane/deliver GitHub issue: https://github.com/fastlane/fastlane/issues/7142

**Comment by singhamit089** [comment]
@viktorbenei that worked thanks 👍

**Comment by viktorbenei** [comment]
Awesome, thanks for reporting! @singhamit089 ;)
