### ISSUE TITLE
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager. 

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/build.issues#11]
# Bitrise Build Issue Report template

## Description of the issue

Error: `Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager. `

## Environment:

Where did the issue happen?

- If on Bitrise.io: which stack? YES

Which build Step causes the issue and which version of the step?

Gradle Runner

## Reproducibility

- Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build) - NO
- Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can **delete all the caches** on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches). - NO
- Does upgrading the build Step to the latest version help? - NO

### Linux/Android stack builds

- Can it be reproduced by running the build locally, __after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)__ and running the build from there with the Bitrise CLI ( https://www.bitrise.io/cli )? If no, can it be reproduced with Docker (using the same docker images / environment we use on bitrise.io)? Related guide: http://blog.bitrise.io/2016/08/08/debug-your-android-linux-builds-locally-with-docker.html

YES

## Build log

```
...
Android SDK Build-Tools 25.0.1. 
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager. 
Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
....

**Comment by viktorbenei** [comment]
If a package is auto installed by Gradle in the system, you still have to accept the licenses.

In a CI system the easiest automated way is to copy the license files from your Mac/PC into the CI system's android licenses directory.

Related docs: https://bitrise-io.github.io/devcenter/android/frequent-android-issues/#alternative-solution-for-the-license-error

Locate the licenses on your Mac/PC:

>    If you have accepted the license agreements on one workstation, but wish to build your projects on a different one, you can export your licenses by copying the accepted licenses folder from the Android Sdk Home folder (this should be located at <android sdk home path>/licenses) of your current workstation, to the Android Sdk Home directory of the machine where you now want to build your projects.

Create an android-licenses directory in the root directory of your git repository, and copy the license files into this directory, then in your Workflow copy the licenses to the right location using a Script step.

Add the Script step right after the Git Clone step (that's when your code is available on the build virtual machine), with the content:

```
#!/bin/bash
# fail if any commands fails
set -e
# debug log
set -x

rsync -avhP ./android-licenses/ "$ANDROID_HOME/licenses/"
```

That's all, this script copies the licenses from the android-licenses (from your repository) into the system's Android SDK Home path under licenses directory.

**Comment by zeinabmohamed** [comment]
@viktorbenei 

Hello ,  i try this script but 
failed in this command 
"rsync -avhP ./android-licenses/ "$ANDROID_HOME/licenses/"

do u suggest any solutions please !! 

-Error
rsync: change_dir "/bitrise/src//./android-licenses" failed: No such file or directory (2)
sent 20 bytes  received 12 bytes  64.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1

**Comment by viktorbenei** [comment]
Hi @zeinabmohamed ,

Please use our **Install missing Android SDK components** step instead of the script, that will help ;)
