### ISSUE TITLE
Xcode archive step error - ReactNative - ld: library not found for ...

### ISSUE THREAD

**Issue by ilyoff** [bitrise-io/build.issues#15]
# Bitrise Build Issue Report template

## Description of the issue

Hello everyone. 

I'm trying to deploy my react-native app for ios. On xcode archive step I got the error:
```Check dependencies
No profiles for 'com.mybizup.bizUp' were found:  Xcode couldn't find a provisioning profile matching 'com.mybizup.bizUp'.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'

** ARCHIVE FAILED **


The following build commands failed:
    Check dependencies
(1 failure)

```

I replaced provisioning profile file and code signing identity file generated by my own with files generated by recommended CODESIGNDOC. Now I'm getting another error and don't know what to do:
```The following build commands failed:
    Ld /Users/vagrant/Library/Developer/Xcode/DerivedData/BizUp-hhhfardivlkpgrajciprqmnlerze/Build/Intermediates/ArchiveIntermediates/BizUp/IntermediateBuildFilesPath/BizUp.build/Release-iphoneos/BizUp.build/Objects-normal/armv7/BizUp normal armv7
    Ld /Users/vagrant/Library/Developer/Xcode/DerivedData/BizUp-hhhfardivlkpgrajciprqmnlerze/Build/Intermediates/ArchiveIntermediates/BizUp/IntermediateBuildFilesPath/BizUp.build/Release-iphoneos/BizUp.build/Objects-normal/arm64/BizUp normal arm64
(2 failures)
```

## Environment:

__Where did the issue happen?__

I'm using Bitrise.io with [Xcode 8.0.x, on OS X 10.11 El Capitan](https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-8.0.x.log) 

__Which build Step causes the issue and which version of the step?__
Xcode Archive for iOS 2.0.2 (latest)

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : **NO**
- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : **NO, I'm not using these steps**
- _Does upgrading the build Step to the latest version help?_ : **NO**
- _When did the issue start?_ : **Today, at first setup**

## Build log

[**BUILD LOG**](https://github.com/bitrise-io/build.issues/files/624726/65893669e7c2a5a4.txt)

[raw-xcodebuild-output.txt](https://github.com/bitrise-io/build.issues/files/624742/raw-xcodebuild-output.txt)

**Comment by viktorbenei** [comment]
Based on the error it seems to be a (missing) dependency issue

```
ld: library not found for -lRNFS
```

You should do a clean git clone, into a new directory on your Mac, and see if you can build the project there. Most likely you'll get the same error there.

Another thing worth to check is the Xcode version. You used the Xcode 8.0 stack - do you use Xcode 8.0 on your Mac too?

**Comment by viktorbenei** [comment]
Closing this issue due to we don't have enough information.

@ilyoff feel free to comment / answer my previous questions (above), and we'll reopen this issue
