### ISSUE TITLE
Build error: Could not load file or assembly '...Microsoft.Build.Tasks.v4.0.dll'

### ISSUE THREAD

**Issue by Lux2057** [bitrise-io/build.issues#18]
# Bitrise Build Issue Report template

## Description of the issue

I got error with NuGet download. It seems that the service can't download Microsoft.Build.Tasks.v4.0.dll. On local machine project works fine and Visual Studio creates package.

## Environment:

__Where did the issue happen?__

Xamarin Stable with Xcode 8.1, on macOS 10.12 (Sierra)

__Which build Step causes the issue and which version of the step?__

xamarin-archive@1.1.1   

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : NO
- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : NO
- _If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)_ : every build
- _Does upgrading the build Step to the latest version help?_ : NO
- _When did the issue start?_ : at first app build

## Build log

[4c070429178098e6.zip](https://github.com/bitrise-io/build.issues/files/631392/4c070429178098e6.zip)

**Comment by godrei** [comment]
Hi @Lux2057 ,
sorry for my late response, could you please try the solutions mentioned in this [STO thread](http://stackoverflow.com/questions/20661943/build-on-tfs-2013-failed-but-okay-locally/32659073#32659073)?

**Comment by Lux2057** [comment]
Hi @godrei, thanks, it helped. I think we can close this issue.

**Comment by godrei** [comment]
@Lux2057 ,
could you please link which solution worked for you? It may help others with this issue...

**Comment by viktorbenei** [comment]
This issue was moved to http://discuss.bitrise.io/t/build-error-could-not-load-file-or-assembly-microsoft-build-tasks-v4-0-dll/45

**Comment by viktorbenei** [comment]
Sorry, this was just an auto-migration test which auto closed this issue.. Anyway, feel free to reply here or on discuss.bitrise.io, if you reply here @Lux2057 we can reopen this issue!
