### ISSUE TITLE
iOS Code Signing error - Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “XXX” were found - [Xcode 7.3.1]

### ISSUE THREAD

**Issue by goodbadboy** [bitrise-io/build.issues#2]
# Bitrise Build Issue Report template

## Description of the issue

xcode-archive@1.10.0 (exit code: 1) : I resolve my code signing identity

I uploaded a developer p12 file. It through me code sign in error. Then i upload a distribution p12(Because it indicate Distribution ID). So upload

## Environment:

Where did the issue happen?

- If on Bitrise.io: which stack?

> Xcode 7.3.x stack

Which build Step causes the issue and which version of the step?

> xcode-archive@1.10.0

## Reproducibility

- Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build) - __NO__
- Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can **delete all the caches** on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches). - __NO__
- Does upgrading the build Step to the latest version help? - __NO__

### Linux/Android stack builds

`-`

### Other stacks

- Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC) and running the build from there with the CLI?

No

## Build log

Please attach the build log (you can download the build log from the build's page,
once the build is finished, using the "Download log" button - floating at the bottom right corner of the log viewer),
__or if you can't attach the whole log__ then the related step's build log, or as much as you can share.

Relevant parts of the logs:

Build log:

```
▸ Check Dependencies

❌  Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “KHMHFG2U43” were found.


** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

`raw-xcodebuild-output` log:

```
Check dependencies
Code Sign error: No code signing identities found: No valid signing
identities (i.e. certificate and private key pair) matching the team
ID “XXXXX” were found.
```

**Comment by viktorbenei** [comment]
What's the content of the `raw-xcodebuild-output.log` file? 
It's attached to the build by the Deploy to Bitrise.io step

**Comment by goodbadboy** [comment]
This is my raw-xcodebuild-output.
[raw-xcodebuild-output.pdf](https://github.com/bitrise-io/build.issues/files/598102/raw-xcodebuild-output.pdf)

Thanks

**Comment by viktorbenei** [comment]
Relevant parts of the logs:

## Build log:

```
▸ Check Dependencies

❌  Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “KHMHFG2U43” were found.


** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

## Raw xcodebuild output log:

```
Check dependencies
Code Sign error: No code signing identities found: No valid signing
identities (i.e. certificate and private key pair) matching the team
ID “KHMHFG2U43” were found.
```

## Next steps

As the build fails in the build/archive section (before the Xcode Export would start), it usually means that the uploaded code signing files are not enough for the full Xcode archive+export process.

Please follow these steps:

1. Do a clean git clone of your repository (on your Mac), into a new directory
1. Open the same Xcode project you specified on bitrise.io
1. Do a full Xcode Archive + Export, until you get a signed IPA
1. Then run `codesigndoc` ( https://github.com/bitrise-tools/codesigndoc#one-liner ) to collect the required signing files
1. Upload __all__ the code signing files `codesigndoc` exports to bitrise.io
1. Start a new build

**Comment by viktorbenei** [comment]
User reported that following the above steps solved the issue
