### ISSUE TITLE
Native iOS (Swift and ObjC) Deploy build failing

### ISSUE THREAD

**Issue by pouriaalmassi** [bitrise-io/build.issues#20]
# Bitrise Build Issue Report template

## Description of the issue

Possible duplicate of #19 .

## Environment:

__Where did the issue happen?__

_If on Bitrise.io: which stack? If not on Bitrise.io: on what operating system? (Plus any other information you can share)_

Stack: Xcode 8.x, on macOS 10.12 (Sierra)

__Which build Step causes the issue and which version of the step?__

Step: deploy-to-itunesconnect-deliver 
Version: 2.6.3

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : NO

- _Does a rebuild without caches help? NO

I opted to *delete all the caches*.  

- _If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)_ : NA. Issue happens consistently not sporadically. 

- _Does upgrading the build Step to the latest version help?_ : NO

- _When did the issue start?_ : After adding the deploy-to-itunesconnect-deliver step. 

## Build log

Build log sent via private channel with this GitHub issue link.

**Comment by viktorbenei** [comment]
Wrong code signing, based on the bundle ID at least. 

The error in the log:

```
Could not find app with app identifier 'com.X.Y.adhoc' in your iTunes Connect account REDACTED - Team: 11...8
```

And in the Xcode Archive step log, you can see that you specified ad how as the export type:

```
ExportMethod: ad-hoc
```

You can only upload App Store signed apps to app store / test flight.

**Comment by viktorbenei** [comment]
I'll close this issue, but if you have any question / comment @pouriaalmassi just ask and we'll reopen it!
