### ISSUE TITLE
Intermittent Xamarin android package download failure

### ISSUE THREAD

**Issue by freever** [bitrise-io/build.issues#23]
# Bitrise Build Issue Report template

## Description of the issue

_Please describe the issue here_
Every now and again a build fails on our Xamarin Android app because the build server fails to download one of the Android support packages. These packages are quite large, so there is probably a reasonable chance that connectivity will be interrupted during the course of the download. 

The relevant snippet of the build log is here:

error XA5208: Download failed. Please download https://dl-ssl.google.com/android/repository/android_m2repository_r38.zip and put it to the /Users/vagrant/.local/share/Xamarin/Xamarin.Android.Support.Animated.Vector.Drawable/24.2.1 directory.
: error XA5208: Reason: An exception occurred during a WebClient request.
				  Downloading https://dl-ssl.google.com/android/repository/android_m2repository_r38.zip into /Users/vagrant/.local/share/Xamarin/zips
: error XA5207: Please install package: 'Xamarin.Android.Support' available in SDK installer. Java library file /Users/vagrant/.local/share/Xamarin/Xamarin.Android.Support.Animated.Vector.Drawable/24.2.1/content/classes.jar doesn't exist.

## Environment:

__Where did the issue happen?__

_If on Bitrise.io: which stack? If not on Bitrise.io: on what operating system? (Plus any other information you can share)_
Xamarin Stable with Xcode 8.1, on macOS 10.12 (Sierra)

__Which build Step causes the issue and which version of the step?__
xamarin-test-cloud-for-ios 2.1.0
I am pretty sure it also happens on the latest Xamarin build step

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : YES/NO
YES - it's an intermittent problem

- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : YES/NO
um, don't know

- _If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)_ :
about 20-30% of builds
- _Does upgrading the build Step to the latest version help?_ : YES/NO
- _When did the issue start?_ :

### Linux/Android stack builds

_Can it be reproduced by running the build locally, **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the Bitrise CLI ( https://www.bitrise.io/cli )? If no, can it be reproduced with Docker (using the same docker images / environment we use on bitrise.io)? Related guide: http://blog.bitrise.io/2016/08/08/debug-your-android-linux-builds-locally-with-docker.html ._
IT does happen locally too sometimes, because the download can be interrupted. 

### Other stacks

_Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the CLI ( https://www.bitrise.io/cli )?_

## Build log

_Please attach the build log (you can download the build log from the build's page,
once the build is finished, using the "Download log" button - floating at the bottom right corner of the log viewer),
**or if you can't attach the whole log** then send the **full log** through a private channel (e.g. email - https://www.bitrise.io/contact ), **with a link to the related GitHub issue**._

**Comment by viktorbenei** [comment]
Thanks for the report @freever !

@godrei 👀

**Comment by freever** [comment]
Thanks for the script to work around this problem, I'll let you know how it goes

**Comment by viktorbenei** [comment]
@freever can you please include the script you used here, as a reference for others if they'd have the same issue?

**Comment by godrei** [comment]
Based on this article: [Resolving Library Installation Errors](https://developer.xamarin.com/guides/android/troubleshooting/resolving-library-installation-errors/)

From the build log:

```
: error XA5208: Download failed. Please download https://dl-ssl.google.com/android/repository/android_m2repository_r38.zip and put it to the /Users/vagrant/.local/share/Xamarin/Xamarin.Android.Support.Animated.Vector.Drawable/24.2.1 directory.
```

we would need `Xamarin.Android.Support.Animated.Vector.Drawable/24.2.1`  installed properly.

This script manually installs it:

```
#!/bin/bash
set -ex

android_m2_repository_url="https://dl-ssl.google.com/android/repository/android_m2repository_r38.zip"
android_dep_pth="/Users/vagrant/.local/share/Xamarin/Xamarin.Android.Support.Animated.Vector.Drawable/24.2.1"

if [ -d "$android_dep_pth" ]; then
  # clean up dependency dir, it may invalid
  rm -rf $android_dep_pth
  mkdir $android_dep_pth
fi

# m2_repository install path
zips_pth="/Users/vagrant/.local/share/Xamarin/zips"
hash="$($android_m2_repository_url | md5 -r)"
file_pth="$zips_pth/$hash.zip"

if [ -d "$zips_pth" ] ; then
  ls "$zips_pth"
else
  mkdir "$zips_pth"
fi

# download it
curl -o "$file_pth" "$android_m2_repository_url"

ls "$zips_pth"
```

**Comment by viktorbenei** [comment]
Awesome, thanks @godrei !

Just one note - I'd replace `curl -o` with `wget -O`, as `curl -o`'s exit code won't be non zero if it can't find the file for example, only for "internal" curl errors (AFAIK)

`wget`'s exit codes are way more predictable

**Comment by freever** [comment]
Here's an updated script - the md5 hash was incorrect

#!/bin/bash

set -ex

android_m2_repository_url="https://dl-ssl.google.com/android/repository/android_m2repository_r38.zip"

android_dep_pth="$HOME/.local/share/Xamarin/Xamarin.Android.Support.Animated.Vector.Drawable/24.2.1"

# clean up dependency dir, it may invalid

if [ -d "$android_dep_pth" ]; then

  rm -rf $android_dep_pth

  mkdir $android_dep_pth

fi

# m2_repository install path

zips_pth="/Users/vagrant/.local/share/Xamarin/zips"

hash="$(echo -n $android_m2_repository_url | md5 -r)"

file_pth="${zips_pth}/${hash}.zip"

if [ -d "$zips_pth" ] ; then

  ls "$zips_pth"

else

  mkdir "$zips_pth"

fi

# download it

wget –q -O "$file_pth" "$android_m2_repository_url"

ls "$zips_pth"

**Comment by godrei** [comment]
Thanks @freever ,
just only one update, based on @viktorbenei 's mentions:

zips_pth="/Users/vagrant/.local/share/Xamarin/zips" -> zips_pth="$HOME/.local/share/Xamarin/zips"

The updated script:

```
#!/bin/bash
set -ex

android_m2_repository_url="https://dl-ssl.google.com/android/repository/android_m2repository_r38.zip"
android_dep_pth="$HOME/.local/share/Xamarin/Xamarin.Android.Support.Animated.Vector.Drawable/24.2.1"

# clean up dependency dir, it may invalid
if [ -d "$android_dep_pth" ]; then
  rm -rf $android_dep_pth
  mkdir $android_dep_pth
fi

# m2_repository install path
zips_pth="$HOME/.local/share/Xamarin/zips"
hash="$(echo -n $android_m2_repository_url | md5 -r)"
file_pth="${zips_pth}/${hash}.zip"

if [ -d "$zips_pth" ] ; then
  ls "$zips_pth"
else
  mkdir "$zips_pth"
fi

# download it
wget -q -O "$file_pth" "$android_m2_repository_url"

ls "$zips_pth"
```
