### ISSUE TITLE
Git clone fails and missing reference errors

### ISSUE THREAD

**Issue by Maggern3** [bitrise-io/build.issues#24]
## Description of the issue

Build fails, perhaps related to git clone failure?
Get's a lot of missing reference errors CS0246. This could be accurate if the repo isn't cloned freshly.

## Environment:

Xamarin Stable with Xcode 8.1, on macOS 10.12 (Sierra) 
Either caused by git clone step or xamarin build(both latest version)

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : NO
- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : No, there's no buttons there for removing cache.

Does upgrading the build Step to the latest version help?_ : NO

Can it be reproduced by running the build locally - It cannot, a clean clone attempt would take a lot of time to test though..

Relevant part of build log
=> git "fetch"
0 attempt failed:
error: RPC failed; curl 56 SSLRead() return error -36
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by viktorbenei** [comment]
Did you solve this issue, that's why you closed it?

**Comment by Maggern3** [comment]
I did, turned out it wasn't a bitrise error. It only appeared on 'release' builds. Perhaps that could be a valuable part of the issue template? Something like 'did you try building for release locally?'. The difference is not obvious at first.

I had moved a library but the references weren't updated correctly even though I removed and added the project through Visual Studio.
The solution was removing all the references to the project and re-adding them.

**Comment by viktorbenei** [comment]
> Perhaps that could be a valuable part of the issue template? 

Definitely! Although I'm not sure what should be included - IMO the "Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli )" question should cover this, given that you run the same workflow locally of course

**Comment by viktorbenei** [comment]
Added a `If you have multiple different build configurations (workflows), does the issue affect all/more than one?` to the Reproducibility section of the template - I think that, combined with the local CLI build should cover this - https://github.com/bitrise-io/build.issues/pull/29/files

What do you think @Maggern3 ?
