### ISSUE TITLE
Unable to deploy a xamarin iOS app to appetize.io

### ISSUE THREAD

**Issue by cbutton1** [bitrise-io/build.issues#25]
I am trying to deploy an iOS sample app to appetize.io and have not been successful.  I have tried using the appetize workflow step as well as uploading the artifact files directly to their site. 

Environment:

On bitrise.io.  Stack chosen by bitrise was "Xamarin Stable with Xcode 8.1, on macOS 10.12 (Sierra)"

Step: (8) appetize-deploy@0.1.3 (exit code: 1)     

Reproducibility

- Does a "Rebuild" help? NO
- Does a rebuild without caches help? NO
- Occurs every time
- Does upgrading the build Step to the latest version help? NO
- When did the issue start? :  12/7/2016

Linux/Android stack builds

Can it be reproduced by running the build locally: NO

Build log

Build log attached.
[231044eea0e01de0.txt](https://github.com/bitrise-io/build.issues/files/639872/231044eea0e01de0.txt)

Note: when I attempted to download artifacts to my local machine and then upload into appetize.io, I get the error: “Error uploading file. Please try again“.  
-	CreatedCardValidator.iOS.ipa
-	CreditCardValidator.iOS.app.dSYM.zip

In the upload page is says: “For iOS, upload a .zip or .tar.gz file containing your compressed .app bundle”
but the zip artifact does not contain an app folder.

**Comment by viktorbenei** [comment]
Thanks for the issue report @cbutton1 !

@godrei please advise here!

**Comment by godrei** [comment]
Hi @cbutton1 ,
i think you provided `bin/iPhone/Debug/CreditCardValidator.iOS.app` as `app_path` input value for the step. But that path is not exists. 
The proper path would be: `/Users/vagrant/git/CreditCardValidator.iOS/bin/iPhone/Debug/CreditCardValidator.iOS.app`, or more better would be: `$BITRISE_SOURCE_DIR/CreditCardValidator.iOS/bin/iPhone/Debug/CreditCardValidator.iOS.app`.

Regarding to manual upload issue:

I assume you tried to upload the `CreditCardValidator.iOS.app.dSYM.zip` file, which is a compressed dsym directory, not a compressed app directory, in your build log: 
`dsym path (/Users/vagrant/deploy/CreditCardValidator.iOS.app.dSYM.zip) is available in (BITRISE_DSYM_PATH) environment variable`.

**Comment by godrei** [comment]
I'll close this issue, but if you need more info/help just let us know and we'll reopen it!

**Comment by cbutton1** [comment]
Using that path worked and I was able to get a working app in appetize.io once I changed bitrise.yaml to use iPhoneSimulator (BITRISE_XAMARIN_PLATFORM: iPhoneSimulator).

Thanks for your help.

**Comment by viktorbenei** [comment]
Thanks for reporting the solution @cbutton1 ! ;)
