### ISSUE TITLE
Intermittent weird test failures (ServiceConfigurationError)

### ISSUE THREAD

**Issue by maoueh** [bitrise-io/build.issues#28]
# Bitrise Build Issue Report template

## Description of the issue

For the same commit, three builds in a row, test fails very weirdly in middle build. There were all run in same hour window.

Example of failures:

```
com.acme.test.Data > testWriteData 
java.lang.RuntimeException
        Caused by: java.lang.NullPointerException

com.acme.test.Other > testSomething 
    java.util.ServiceConfigurationError
```

Lots of test are failing when it happen: `224 tests completed, 130 failed, 4 skipped`.

I thought first about a problem in my tests but the failures are so much unrelated to each other that it's sure there is something more global going on. Specially the weird `java.util.ServiceConfigurationError` error.

I already experienced similar issue with other project but do not have any link to failing builds at hand.

## Environment:

Build step causing the issue is `gradle-runner` step invoking a test task.

Running on Android stack Ubuntu 16.04 Android & Docker.

## Reproducibility

The issue is hard to reproduce and never experienced in my local setup using `bitrise run pr`. I would say it does not happen often but we get around 10 or more by month (~300 android builds).

### Linux/Android stack builds

Clearly not locally on my OS X computer. Will check for using Docker and use your image running it multiple times. That's a good idea.

[logs.zip](https://github.com/bitrise-io/build.issues/files/641043/logs.zip)

## Thoughts

I'm wondering if it could be a cache problem as a push/pull my Gradle build folder from build to build. 

Maybe I never was able to reproduce locally because I do not run test locally often enough.

My first investigation leads me to think it's related with `Robotelectric` as it seems to use `ServiceConfigurationError`. Seen this error which looks promising:

 * https://github.com/robolectric/robolectric/issues/2379 

Clearly I need to fire up Docker and try replicate.

Maybe you guys seen this issue already?

**Comment by viktorbenei** [comment]
> Maybe you guys seen this issue already?

I'm not aware of, unfortunately.

> Clearly I need to fire up Docker and try replicate.

Indeed I'd say that's the best way to go forward, as the issue seems to be either unit test (code) related, or maybe a tool (version) you use. The docker reproduction guide should be helpful (https://bitrise-io.github.io/devcenter/docker/run-your-build-locally-in-docker/).

Please let us know how it goes, if you can find a solution or if you can't - a solution can help others in the future!

**Comment by maoueh** [comment]
I fired up the container and make an initial test, it passed.

Will need to run it multiple times in a loop to see if I can "reproduce" somehow.

**Comment by viktorbenei** [comment]
This issue was moved to http://discuss.bitrise.io/t/intermittent-weird-test-failures-serviceconfigurationerror/47

**Comment by viktorbenei** [comment]
Sorry, this was just an auto-migration test which auto closed this issue.. Anyway, feel free to reply here or on discuss.bitrise.io, if you reply here we'll reopen this issue here!
