### ISSUE TITLE
Invalid Swift Support - The SwiftSupport folder is missing

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/build.issues#31]
# Bitrise Build Issue Report template

## Description of the issue

Published a build to iTunes Connect from bitrise, and then I got an email:

```
Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.
```

## Environment:

__Where did the issue happen?__

Xcode stack

__Which build Step causes the issue and which version of the step?__

Deploy to iTunes Connect / TestFlight

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : NO
- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : NO
- _If you have multiple different build configurations (workflows), does the issue affect all/more than one?_ : YES
- _Does upgrading the build Step to the latest version help?_ : NO

**Comment by viktorbenei** [comment]
Solution:

I've tried to archive with configuration where `EMBEDED_CONTENT_CONTAINS_SWIFT` was set to `YES`. But it should be set to `NO`. :)

**Comment by markrufino-cp** [comment]
Leaving a random helpful comment here for others that might encounter a similar issue, this can also happen if you've accidentally set your "distribution type" to "ad-hoc" (for provisioning step) but your "export method" is "app-store" (for the archive & export step)

**Comment by viktorbenei** [comment]
Thanks for sharing @markrufino-cp ! 😉
