### ISSUE TITLE
Code signing is required for product type 'App Extension' in SDK 'iOS 10.2'

### ISSUE THREAD

**Issue by Sjoerdjanssenen** [bitrise-io/build.issues#32]
# Bitrise Build Issue Report template

## Description of the issue

I keep getting an error saying `Code signing is required for product type 'App Extension' in SDK 'iOS 10.2'`. I have added all provisioning profiles that your helper tool extracts and I have added my .p12 file. Any suggestions?

## Environment:

Bitrise.io -> Xcode 8.2.x on macOS Sierra. This happens in the Xcode Archive step.

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : NO
- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : NO
- _If you have multiple different build configurations (workflows), does the issue affect all/more than one?_ : NO
- _If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)_ : 100% of the builds
- _Does upgrading the build Step to the latest version help?_ : NO
- _When did the issue start?_ : Last weekend

**Comment by viktorbenei** [comment]
Closing as we did not receive a reply - @Sjoerdjanssenen please let us know if we can help with anything and we'll reopen this issue!

**Comment by viktorbenei** [comment]
Note for future reference: switching to Manual Code Signing in Xcode works - that way you can specify exactly which signing files should be used, instead of using Xcode's Automatic Code signing (where Xcode selects files automatically/in the background for the _initial_ signing)
