### ISSUE TITLE
Android build failure: OutOfMemoryError

### ISSUE THREAD

**Issue by clementhely** [bitrise-io/build.issues#34]
# Bitrise Build Issue Report template

## Description of the issue

Our Android builds started failing sometimes recently, and it seems to happen more and more often as the code base grows. The problem seems to be related to java heap size, as we get `OutOfMemoryError`s. Here is the stacktrace:

```
:app:mergeFullDebugJniLibFolders
:app:transformNative_libsWithMergeJniLibsForFullDebug
:app:transformNative_libsWithStripDebugSymbolForFullDebug
:app:processFullDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForFullDebug
:app:validateSigningFullDebug
:app:packageFullDebugException in thread "pool-352-thread-1" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
	at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at com.android.builder.internal.packaging.zip.compress.DeflateExecutionCompressor.immediateCompress(DeflateExecutionCompressor.java:70)
	at com.android.builder.internal.packaging.zip.compress.ExecutorCompressor.lambda$compress$0(ExecutorCompressor.java:55)
	at com.android.builder.internal.packaging.zip.compress.ExecutorCompressor$$Lambda$232/1310844487.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-352-thread-2" java.lang.OutOfMemoryError: Java heap space
	at java.lang.Object.clone(Native Method)
	at com.google.common.io.ByteSource$ByteArrayByteSource.read(ByteSource.java:520)
	at com.android.builder.internal.packaging.zip.utils.CloseableDelegateByteSource.read(CloseableDelegateByteSource.java:136)
	at com.android.builder.internal.packaging.zip.compress.DeflateExecutionCompressor.immediateCompress(DeflateExecutionCompressor.java:70)
	at com.android.builder.internal.packaging.zip.compress.ExecutorCompressor.lambda$compress$0(ExecutorCompressor.java:55)
	at com.android.builder.internal.packaging.zip.compress.ExecutorCompressor$$Lambda$232/1310844487.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-352-thread-3" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-352-thread-4" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-352-thread-5" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-352-thread-6" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-352-thread-7" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-352-thread-8" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-352-thread-9" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-352-thread-10" java.lang.OutOfMemoryError: Java heap space
```

It seems that our `gradle.properties` is being ignored, as we see this message in the logs:
```
:app:transformClassesWithDexForFullDebug

Running dex as a separate process.

To run dex in process, the Gradle daemon needs a larger heap.
It currently has 1024 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to at least 4608 MB (based on the dexOptions.javaMaxHeapSize = 4096M).
To do this set org.gradle.jvmargs=-Xmx4608M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html
```
Despite having the following `gradle.properties` file:
```
# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Settings specified in this file will override any Gradle settings
# configured through the IDE.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx10248m -XX:MaxPermSize=256m
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
org.gradle.parallel=true

org.gradle.configureondemand=true
```

We also tried with `org.gradle.jvmargs=-Xmx4608M`, but got the same message.

Our project contains a main `app` module and about 40 other, smaller modules.

## Environment:

__Where did the issue happen?__

Happens on this stack: Android & Docker, on Ubuntu 16.04

__Which build Step causes the issue and which version of the step?__

During a simple Gradle Runner step, which executes the following tasks: `assembleFullDebug crashlyticsUploadDistributionFullDebug` on our `app` module. The problem always seems to happen when running the `packageFullDebug` task.

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : NO, it used to sometimes help, but now seems to consistently fail (likely because our app grew quite a bit)
- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : NO, we used not to use cache, when the issue appeared I tried setting up the caching steps, but that did not help has the build keeps failing.
- _If you have multiple different build configurations (workflows), does the issue affect all/more than one?_ : We only use one workflow
- _If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)_ : I'd say it used to happen about 20% of the time on our main branch, now that we are trying to build from another branch it happens 100% of the time.
- _Does upgrading the build Step to the latest version help?_ : NO, we are already running the latest version
- _When did the issue start?_ : about 3/4 months ago

### Linux/Android stack builds

_Can it be reproduced by running the build locally, **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the Bitrise CLI ( https://www.bitrise.io/cli )? If no, can it be reproduced with Docker (using the same docker images / environment we use on bitrise.io)? Related guide: https://bitrise-io.github.io/devcenter/docker/run-your-build-locally-in-docker/ ._

Local builds work. We used to have memory issues as well, but setting `org.gradle.jvmargs=-Xmx4608M` in the `gradle.properties` solved it.

### Other stacks

_Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the CLI ( https://www.bitrise.io/cli )?_

I will try that now and update this issue.

## Build log

_Please attach the build log (you can download the build log from the build's page,
once the build is finished, using the "Download log" button - floating at the bottom right corner of the log viewer),
**or if you can't attach the whole log** then send the **full log** through a private channel (e.g. email - https://www.bitrise.io/contact ), **with a link to the related GitHub issue**._

Sending the logs through private channel

**Comment by viktorbenei** [comment]
Please follow this guide: http://devcenter.bitrise.io/android/android-tips-and-tricks/#memory-ram-limit and set both limits, using environment variables.

Let us know how it goes!

**Comment by clementhely** [comment]
Thank you for your reply.
Setting the properties as environment variables worked fine! 👍 

I guess you can close this issue. :)

**Comment by viktorbenei** [comment]
Glad to hear that it worked - thanks for reporting both the issue and the solution/confirmation! ;)

**Comment by nagad814** [comment]
@viktorbenei can direct me how to set these environment variables. I have gone through this link already http://devcenter.bitrise.io/android/android-tips-and-tricks/#memory-ram-limit

**Comment by viktorbenei** [comment]
Just add them in Env Vars, e.g. as App Env Vars in the workflow editor

1. open the app on bitrise.io
1. open the workflow editor (click the Workflow tab)
1. in the editor switch to the Env Vars tab
1. specify the env var items in the **App Environment Variables** section

Let us know if you'd have any questions @nagad814 ! :)

**Comment by sleeke** [comment]
Quick note to anyone else who comes here; the quotes should be omitted:

Key: ```_JAVA_OPTIONS```
Value: ```-Xms512m -Xmx1024m```

Key: ```GRADLE_OPTS ```
Value: ```-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"```

**Comment by viktorbenei** [comment]
@sleeke thanks for sharing! :)

**Comment by subzthanabalan** [comment]
Updated link to tips & tricks section: https://devcenter.bitrise.io/tips-and-tricks/android-tips-and-tricks/#memory-ram-limit

**Comment by viktorbenei** [comment]
Thanks @subzthanabalan ! :)

**Comment by FantasyCooper** [comment]
why not remove the quote in the wiki:
https://devcenter.bitrise.io/tips-and-tricks/android-tips-and-tricks/#Memory%20(RAM)%20limit

confusing

**Comment by PaulWoitaschek** [comment]
> Updated link to tips & tricks section: https://devcenter.bitrise.io/tips-and-tricks/android-tips-and-tricks/#memory-ram-limit

With the "" you included, the builds will fail. @sleeke gave me the clue why my builds failed.

**Comment by danielgomezrico** [comment]
@FantasyCooper  the link is broken, it is https://devcenter.bitrise.io/tips-and-tricks/android-tips-and-tricks/#memory-ram-limit

**Comment by sternetj** [comment]
For anyone else that comes here: https://web.archive.org/web/20180209043439/http://devcenter.bitrise.io/android/android-tips-and-tricks/
