### ISSUE TITLE
java.lang.UnsupportedOperationException when using multidex

### ISSUE THREAD

**Issue by huytq209** [bitrise-io/build.issues#36]
# Bitrise Build Issue Report template

## Description of the issue

Pls see attached log file

## Environment:

Android & Docker on Ubuntu 16.04

## Reproducibility

it happened in every builds

### Linux/Android stack builds

Local build is working without this issue

## Build log

[f99e8f2ca0fcfbab.txt](https://github.com/bitrise-io/build.issues/files/654122/f99e8f2ca0fcfbab.txt)

**Comment by viktorbenei** [comment]
Does it happen if you do a clean git clone on your Mac/PC, into a new directory, and you run the `gradlew` command there?

**Comment by huytq209** [comment]
yes, it does.

**Comment by viktorbenei** [comment]
> yes, it does.

Did you manage to solve the issue locally? Once you solve it there and commit & push the changes, it should work on bitrise.io too

**Comment by viktorbenei** [comment]
Closing as we did not receive a reply in 5 days now - @huytq209 feel free to reply here, and if required we'll of course reopen this issue!

**Comment by viktorbenei** [comment]
Also, if you managed to fix the issue, please share what the fix was, to help others who have a similar issue in the future!
