### ISSUE TITLE
Error launching instruments: Instruments crashed on startup

### ISSUE THREAD

**Issue by bisonhubert** [bitrise-io/build.issues#37]
# Bitrise Build Issue Report template

## Description of the issue

I'm attempting to run Appium UI tests on the iOS workflow of my native mobile application. The emulator is unable to run the app, as Instruments crashes on startup.

## Environment:

Stack: Xcode 7.3.1 on OS X 10.11 El Capitan - LTS Stack
Failing step: Custom script running Appium test on iOS
Previous steps: Create and copy a build to run tests against

## Reproducibility

I'm unable to reproduce this error locally. In the server logs, the tests attempt to boot the Xcode simulator 5 times before the number of retries is reached. This issue happens every time I try to run the tests, whether I'm using a .ipa or .app build.

## Build log

[f9f26a5ae872d34d.txt](https://github.com/bitrise-io/build.issues/files/656075/f9f26a5ae872d34d.txt)

**Comment by viktorbenei** [comment]
Can you provide a sample project and config what we could use to reproduce this issue?

**Comment by viktorbenei** [comment]
Also, did you check the `/Users/vagrant/git/npm-debug.log` file?

```
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vagrant/git/npm-debug.log
```

You can attach it to the build with a `Deploy to Bitrise.io` step - just add it after this step, and specify this file's path (`/Users/vagrant/git/npm-debug.log`) - related guide: http://devcenter.bitrise.io/tips-and-tricks/attach-any-file-to-build/

**Comment by viktorbenei** [comment]
Closing as we did not receive a reply - @bisonhubert please let us know if we can help with anything and we'll reopen this issue!
