### ISSUE TITLE
Cocoapod Modules not Found

### ISSUE THREAD

**Issue by RichAppz** [bitrise-io/build.issues#38]
# URGENT - Cocoapod Modules not Found

## Description of the issue

When running Xcode tests, after pod installation, the Modules are not being found and failing. This is not the case on Local

`/Users/vagrant/git/<ProjectName>/<ProjectName>.h:20:9: error: module 'Alamofire' not found
@import Alamofire;
        ^
<unknown>:0: error: could not build Objective-C module '<ProjectName>'`

## Environment:

__Where did the issue happen?__

Xcode 8.2 (Sierra) Test run

_If on Bitrise.io: which stack? If not on Bitrise.io: on what operating system? (Plus any other information you can share)_

__Which build Step causes the issue and which version of the step?__

Run Cocoapod Install - Always Latest Version 
Xcode Test - Always Latest Version

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : YES/NO

Rebuild never helps

- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : YES/NO

Not caching

- _If you have multiple different build configurations (workflows), does the issue affect all/more than one?_ : YES/NO

Yes this is happening on ALL projects at the moment

- _If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)_ :

100% 

- _Does upgrading the build Step to the latest version help?_ : YES/NO

No

- _When did the issue start?_ :

Few weeks now

### Linux/Android stack builds

_Can it be reproduced by running the build locally, **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the Bitrise CLI ( https://www.bitrise.io/cli )? If no, can it be reproduced with Docker (using the same docker images / environment we use on bitrise.io)? Related guide: https://bitrise-io.github.io/devcenter/docker/run-your-build-locally-in-docker/ ._

Nope

### Other stacks

_Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the CLI ( https://www.bitrise.io/cli )?_

Nope

## Build log

_Please attach the build log (you can download the build log from the build's page,
once the build is finished, using the "Download log" button - floating at the bottom right corner of the log viewer),
**or if you can't attach the whole log** then send the **full log** through a private channel (e.g. email - https://www.bitrise.io/contact ), **with a link to the related GitHub issue**._

**Logs are private sorry, please request**

**Comment by viktorbenei** [comment]
If you use `CocoaPods`, you have to build/use the `.xcworkspace`, not the `.xcodeproj`. You most likely have the "project path" configured in your App Env Vars, with the key `BITRISE_PROJECT_PATH` - just change the __value__ (the key should remain `BITRISE_PROJECT_PATH`!) from `X.xcodeproj` to `X.xcworkspace`.


Relevant parts of the log:

```
+------------------------------------------------------------------------------+
| (4) xcode-test@1.18.1                                                        |
+------------------------------------------------------------------------------+
| id: xcode-test                                                               |
| version: 1.18.1                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2016-12-16T06:29:42-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
[34mINFO[0m[06:29:42]  * [32;1m[OK][0m Step dependency (xcode) installed, available. 
[34mINFO[0m[06:29:42]  * [32;1m[OK][0m Step dependency (go) installed, available. 

[34;1mProject Parameters:[0m
- ProjectPath: REDACTED.xcodeproj
...

...
| [32;1m✓[0m | [32;1mcocoapods-install[0m                                             | 18 sec   |
+---+---------------------------------------------------------------+----------+
| [31;1mx[0m | [31;1mxcode-test@1.18.1 (exit code: 1)[0m                              | 69 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-xcode-test/issues         |
| Source: https://github.com/bitrise-io/steps-xcode-test                       |
...
```

**Comment by RichAppz** [comment]
Perfect, don't know why that has started defaulting to that value. Thanks

**Comment by viktorbenei** [comment]
My guess is that when you did the initial setup of the project you did not have CocoaPods (Podfile) in your repository, and you added that later. This environment variable is set/generated during the app setup, and not changed after that, unless you change it.

**Comment by viktorbenei** [comment]
Thanks for reporting btw, I'm sure this will help others in the future! ;)
