### ISSUE TITLE
Cannot start android emulator

### ISSUE THREAD

**Issue by suguru** [bitrise-io/build.issues#39]
## Description of the issue

I can't start the android emulator from a few days ago. When I tried to start the emulator, `error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory` error has happened always. I didn't change build yml.

## Environment:

__Where did the issue happen?__

Bitrise stack: Android & Docker, on Ubuntu 16.04

__Which build Step causes the issue and which version of the step?__

```
    - create-android-emulator@1.0.0:
        inputs:
        - name: android-21
        - platform: android-21
        - custom_hardware_profile_content: ''
    - start-android-emulator@1.1.0: {}
```

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : NO
- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : NO
- _If you have multiple different build configurations (workflows), does the issue affect all/more than one?_ : NOT SURE
- _If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)_ : ALWAYS
- _Does upgrading the build Step to the latest version help?_ : NO
- _When did the issue start?_ : 16/Dec

### Linux/Android stack builds

_Can it be reproduced by running the build locally_: NO. It could start emulator at local bitrise cli.

## Build log

```
+------------------------------------------------------------------------------+
| (5) create-android-emulator@1.0.0                                            |
+------------------------------------------------------------------------------+
| id: create-android-emulator                                                  |
| version: 1.0.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2016-12-17T21:59:31Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[21:59:31] Start installing (golang) with apt-get       
INFO[21:59:31]  * [OK] Step dependency (go) installed, available. 

Configs:
- Name: android-21
- Platform: android-21
- Abi: armeabi-v7a
- Options: 
- CustomHardwareProfileContent:
- AndroidHome: /opt/android-sdk-linux


Check if platform installed
installed: true

Check if system image installed
checking path: /opt/android-sdk-linux/system-images/android-21/armeabi-v7a
checking path: /opt/android-sdk-linux/system-images/android-21/default/armeabi-v7a
installed: true

Creating AVD image

$ android "create" "avd" "--force" "--name" "android-21" "--target" "android-21" "--abi" "armeabi-v7a"

Android 5.0.1 is a basic Android platform.
Do you wish to create a custom hardware profile [no]Created AVD 'android-21' based on Android 5.0.1, ARM (armeabi-v7a) processor,
with the following hardware config:
hw.cpu.model=cortex-a8
hw.lcd.density=240
hw.ramSize=512
vm.heapSize=48
Emaultor name is exported in environment variable: BITRISE_EMULATOR_NAME (value: android-21)
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | create-android-emulator@1.0.0                                 | 10 sec   |
+---+---------------------------------------------------------------+----------+

                                          ▼

+------------------------------------------------------------------------------+
| (6) start-android-emulator@1.1.0                                             |
+------------------------------------------------------------------------------+
| id: start-android-emulator                                                   |
| version: 1.1.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2016-12-17T21:59:41Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |

Configs:
  emulator_name: android-21
  emulator_skin: 768x1280
  emulator_options: -no-boot-anim -no-audio -no-window
  [deprecated!] other_options: 

Starting emulator
  /opt/android-sdk-linux/tools/emulator64-arm -avd android-21 -skin 768x1280 -no-boot-anim -no-audio -no-window
/opt/android-sdk-linux/tools/emulator64-arm: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory

Starting emulator timed out
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | start-android-emulator@1.1.0 (exit code: 1)                   | 13.4 min |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...ub.com/bitrise-steplib/steps-start-android-emulator/issues |
| Source: https://github.com/bitrise-steplib/steps-start-android-emulator      |
+---+---------------------------------------------------------------+----------+
```

**Comment by viperwarp** [comment]
I'm getting the same problem with a pretty much identical build log except that I was using `android-24`

**Comment by viktorbenei** [comment]
We're looking into this

**Comment by viktorbenei** [comment]
A quick fix, while we're working on updating the docker images / VMs:

Drop in a Script step (can be the first step in the workflow) with:

```
sudo apt-get install libqt5widgets5
```

This will install the missing Qt 5 widgets library, the one which causes the error `error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory`

**Comment by viktorbenei** [comment]
Preinstalled fix will be deployed soon.

**Comment by viktorbenei** [comment]
Fix deployed - new builds should now don't have this issue even without the `apt-get` fix.

Thanks for reporting @suguru and sorry for the inconvenience

**Comment by viktorbenei** [comment]
Note: we also added a test build to our stack update samples collection, to ensure that no new Android/Linux stack will be released where the Emulator can't be booted.

**Comment by rhodo79** [comment]
Hello Everyone,

I'm very fresh user of Ubuntu. I tried to start work with Android Studio on it as my new AMD laptop doesn't support virtualisation on windows, but I'm not able to start emulator as I receive following error statements:

/home/rh/Android/Sdk/emulator/emulator64-x86: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.7' not found (required by /home/rh/Android/Sdk/emulator/emulator64-x86)
/home/rh/Android/Sdk/emulator/emulator64-x86: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by /home/rh/Android/Sdk/emulator/emulator64-x86)
/home/rh/Android/Sdk/emulator/emulator64-x86: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by /home/rh/Android/Sdk/emulator/emulator64-x86)
/home/rh/Android/Sdk/emulator/emulator64-x86: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /home/rh/Android/Sdk/emulator/emulator64-x86)
/home/rh/Android/Sdk/emulator/emulator64-x86: /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5: version `Qt_5' not found (required by /home/rh/Android/Sdk/emulator/emulator64-x86)


I already tried to fix it with apt-get fix but still doesn't work. Any ideas how to fix it?

**Comment by viktorbenei** [comment]
@rhodo79 I think all of these steps are required for the ARM emulators: https://github.com/bitrise-docker/android/blob/master/Dockerfile#L149

In short, we install the `libqt5widgets5` apt package, as well as we set the `QT_QPA_PLATFORM` env var to `offscreen` and the `LD_LIBRARY_PATH` env var to include `${ANDROID_HOME}/tools/lib64`.

For future reference, in case someone would read this months later, please check the linked Dockerfile (https://github.com/bitrise-docker/android/blob/master/Dockerfile) as that's our up-to-date "guide", how we configure the environment, which might change when required (we did change it quite a few times).
