### ISSUE TITLE
Wrong provisioning profile chosen for workflow.

### ISSUE THREAD

**Issue by masterwok** [bitrise-io/build.issues#40]
# Bitrise Build Issue Report template

## Description of the issue

I am currently trying to automate the compilation of an iOS build for ad-hoc and production. Currently I am able to get the build process to work for the ad-hoc build. An ad-hoc provisioning profile and a code signing identity have been added. The build issue that I am seeing occurs when I add the distribution provisioning profile for the production build. After adding the provisioning profile both builds complete. However, when I go to install the Ad-Hoc build on my device the install fails with an error stating that it "could not be installed at this time." When checking the build on Hockey I see, "This version was built with an unknown provisioning profile type." It seems like the build is having trouble determining which provisioning profile to choose. How do I configure this?

## Environment:

__Where did the issue happen?__

This issue is occurring on Bitrise.io when adding both an ad-hoc and distribution provisioning profile.

_If on Bitrise.io: which stack? If not on Bitrise.io: on what operating system? (Plus any other information you can share)_

Xamarin Stable with Xcode 8.2, on macOS 10.12 (Sierra)

__Which build Step causes the issue and which version of the step?__

This issue makes itself known when trying to install the app on the device due to the Certificate and profile installer step.

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : YES/NO

Rebuilding does not resolve this issue as the build does not fail. Removing the distribution provisioning profile gets the build installing on the device. Adding the distribution profile alongside the ad-hoc profile causes the build to fail to install.

- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : YES/NO

No.

- _If you have multiple different build configurations (workflows), does the issue affect all/more than one?_ : YES/NO

It makes the ad-hoc build fail when installing. I do not know if this is affecting the distribution build however both builds successfully complete.

- _If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)_ :

100% of the time.

- _Does upgrading the build Step to the latest version help?_ : YES/NO

No.

- _When did the issue start?_ :

When adding the distribution provisioning profile.

## Build log

I've sent an email containing the build log.

**Comment by viktorbenei** [comment]
> However, when I go to install the Ad-Hoc build on my device the install fails with an error stating that it "could not be installed at this time."

From the log you sent:

```
Creating export options for export type: app-store[0m
  * plist_content:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>app-store</string>
</dict>
</plist>
```

This means that you do an App Store Distribution code signing. If an IPA is signed with an App Store distribution profile, it can only be installed from the App Store, and from iTunes Connect TestFlight. There's no other way to install it.

**Comment by viktorbenei** [comment]
I'll close this issue, thank you for the report - if you'd have any questions, please let us know!

**Comment by viktorbenei** [comment]
That said, from the logs it seems that the `app-store` method selection might be an issue in the Xamarin Builder step. From the logs it seems that you specified `development` for the Export Method, and the step still selected `app-store`, most likely because of your Xamarin project configurations.

The best would be to replace the Xamarin Builder step with the new Xamarin Archive step, as the Xamarin Builder step is now in "maintenance" mode and will be deprecated soon. You can find the related blog post with migration notes here: http://blog.bitrise.io/2016/10/18/the-new-xamarin-archive-step.html

**Comment by emeraldimp** [comment]
Can you guys find a way to mark maintenance steps in the workflow editor? There's nothing obvious from using the UI that says to migrate, and honestly "Xamarin Archive" doesn't indicate to me that I would use it to build the project.

**Comment by viktorbenei** [comment]
Definitely, I'll bump the related task
