### ISSUE TITLE
Unable to include libraries in a relative directory

### ISSUE THREAD

**Issue by promomark** [bitrise-io/build.issues#41]
# Bitrise Build Issue Report template

## Description of the issue
I am getting an error when building a project that has a dependent library and headers in a directory that is a sibling to the directory with the XCode project.

_Please describe the issue here_
My setup:

1) XCode project is in <Repository root>/<Project dir>/<Project>.xcodeproj
2) Dependent library header is in <Repository root>/vuforia-sdk-ios/build/include/Vuforia/Vuforia.h

This builds fine in XCode locally, but when built on the server, I get:

/Users/vagrant/git/RedStripeIR-IOS/RedStripeIR/Classes/Features/ImageTargets/ImageTargetsEAGLView.mm:15:9: 'Vuforia/Vuforia.h' file not found

#import <Vuforia/Vuforia.h>

## Environment:

__Where did the issue happen?__

_If on Bitrise.io: which stack? If not on Bitrise.io: on what operating system? (Plus any other information you can share)_

On www.bitrise.io, using stack Xcode 8.2.x, on macOS 10.12 (Sierra)

__Which build Step causes the issue and which version of the step?__

xcode-archive@2.0.4  

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : YES/NO

NO

- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : YES/NO
- _If you have multiple different build configurations (workflows), does the issue affect all/more than one?_ : YES/NO
- _If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)_ :
- _Does upgrading the build Step to the latest version help?_ : YES/NO
- _When did the issue start?_ :

2016-12-19

### Linux/Android stack builds

_Can it be reproduced by running the build locally, **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the Bitrise CLI ( https://www.bitrise.io/cli )? If no, can it be reproduced with Docker (using the same docker images / environment we use on bitrise.io)? Related guide: https://bitrise-io.github.io/devcenter/docker/run-your-build-locally-in-docker/ ._

### Other stacks

_Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the CLI ( https://www.bitrise.io/cli )?_

## Build log

_Please attach the build log (you can download the build log from the build's page,
once the build is finished, using the "Download log" button - floating at the bottom right corner of the log viewer),
**or if you can't attach the whole log** then send the **full log** through a private channel (e.g. email - https://www.bitrise.io/contact ), **with a link to the related GitHub issue**._

**Comment by viktorbenei** [comment]
The issue was a git ignore (in `.global_gitignore`) in this case.

If you have a similar issue, do a clean `git clone` into `/tmp`, and try to build your project from there. This can help to reproduce the issue locally, if it's caused by a missing or ignored dependency, or some other ignored file.
