### ISSUE TITLE
"smudge filter lfs failed" during pod install

### ISSUE THREAD

**Issue by airbob** [bitrise-io/build.issues#42]
## Description of the issue

We have a private pod, and during pod install, in the middle of git clone it has this "smudge filter lfs failed" and then failed the building process

## Environment:

Stack: Bitrise.io Xcode 8.0.x, on OSX 10.11(EI Capitan)
Failed Step: cocoapods-install@1.5.9 (exit code: 1) 

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : **NO**
- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : **NO**
- _If you have multiple different build configurations (workflows), does the issue affect all/more than one?_ : **YES**
- _If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)_ : 100% now
- _Does upgrading the build Step to the latest version help?_ : **NO**
- _When did the issue start?_ : **around 21th Dec, it was working fine last week**

### Linux/Android stack builds

_Can it be reproduced by running the build locally, **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the Bitrise CLI ( https://www.bitrise.io/cli )? If no, can it be reproduced with Docker (using the same docker images / environment we use on bitrise.io)? Related guide: https://bitrise-io.github.io/devcenter/docker/run-your-build-locally-in-docker/ ._

**I can successfully do a pod install with my local machine, but I didn't try this with bitrise CLI locally.**

### Other stacks

_Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the CLI ( https://www.bitrise.io/cli )?_

**I didn't try this with bitrise CLI locally.**

## Build log

_Please attach the build log (you can download the build log from the build's page,
once the build is finished, using the "Download log" button - floating at the bottom right corner of the log viewer),
**or if you can't attach the whole log** then send the **full log** through a private channel (e.g. email - https://www.bitrise.io/contact ), **with a link to the related GitHub issue**._

This is the log snippets that failed:
```
Downloading android/sample/src/main/assets/short_song/bass.wav (4.64 MB)
     Error downloading object: android/sample/src/main/assets/short_song/bass.wav (b96b952ebd40f1461b8c9d8759aeac0d539886305af825058841ae345d0c89b0)

     Errors logged to /private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/d20161221-1250-1g90yv0/.git/lfs/objects/logs/20161221T003116.164904337.log
     Use `git lfs logs last` to view the log.
     error: external filter git-lfs smudge -- %!f(MISSING) failed 2
     error: external filter git-lfs smudge -- %!f(MISSING) failed
     fatal: android/sample/src/main/assets/short_song/bass.wav: smudge filter lfs failed
```

For detailed log I have shared via slack.

**Comment by viktorbenei** [comment]
It seems it's Git LFS related - see: https://github.com/git-lfs/git-lfs/issues/911

You can find a couple of things in that issue (and by searching for `error: external filter git-lfs smudge` in general), but this might actually be a bug which was fixed in a new LFS version.

To upgrade the preinstalled git lfs version please add a Script step before the Git Clone step, with the content:

```
brew upgrade git-lfs
git lfs install
```

The second command is most likely not required, just to be sure ;)

If that wouldn't work, it might worth to try something like the suggestion here: https://github.com/git-lfs/git-lfs/issues/911#issuecomment-169998792

Note: of course you should skip the `git clone` command, that will be done by the Git Clone step, the other commands can be run before & after the Git Clone step with `Script` step(s).

Let us know how it goes, or if you have any questions!
_Thanks for creating the issue report!_

**Comment by airbob** [comment]
Tried 
```
brew upgrade git-lfs
git lfs install
```
but it didn't work for my case

Tried 
```
git lfs install --skip-smudge
```
working

Thanks

**Comment by viktorbenei** [comment]
Thanks for reporting both the issue, and the solution @airbob ! I'm sure it will help others in the future too! ;)
