### ISSUE TITLE
Build started failing at Carthage step - fails to find Cartfile

### ISSUE THREAD

**Issue by heitorfr** [bitrise-io/build.issues#5]
## Description of the issue

Build started failing at Carthage step. I've also tried to build a previous commit that succeeded before but it still fails with the error: 'Failed to read file or folder at /Users/vagrant/git/Cartfile'

## Environment:

Where did the issue happen?

In Bitrise.io, stack: Xcode 8.0.x, on OS X 10.11 (El Capitan)

Which build Step causes the issue and which version of the step?
Carthage, tried both 3.0.0 and 2.4.0

## Reproducibility

Started today and It's consistent.  I'm not using caching. Happens also with the last version of the step.

- Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)

No

- Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can **delete all the caches** on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches).

I'm not using caching 
- If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)

It's consistent

- Does upgrading the build Step to the latest version help?

No

- When did the issue start?

Today 18th November

### Linux/Android stack builds

- Can it be reproduced by running the build locally with Docker (using the same docker images we use on bitrise.io), after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC) and running the build from there? (Related guide: http://blog.bitrise.io/2016/08/08/debug-your-android-linux-builds-locally-with-docker.html )

NA

### Other stacks

- Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC) and running the build from there with the CLI?

## Build log

Please attach the build log (you can download the build log from the build's page,
once the build is finished, using the "Download log" button - floating at the bottom right corner of the log viewer),
__or if you can't attach the whole log__ then the related step's build log, or as much as you can share.

Relevant parts of the log:

```
+------------------------------------------------------------------------------+
| (2) Copy changelog to deploy dir                                             |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.1.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2016-11-18T10:11:02-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
+ cp /Users/vagrant/git/EATMade/Changelog.md /Users/vagrant/deploy
|                                                                              |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mCopy changelog to deploy dir[0m                                  | 4.00 sec |
+---+---------------------------------------------------------------+----------+


...

+------------------------------------------------------------------------------+
| (4) carthage@2.4.0                                                           |
+------------------------------------------------------------------------------+
| id: carthage                                                                 |
| version: 2.4.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2016-11-18T10:11:14-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
[34mINFO[0m[10:11:14]  * [32;1m[OK][0m Step dependency (carthage) installed, available. 
*** No Cartfile.resolved found, updating dependencies
Failed to read file or folder at /Users/vagrant/git/Cartfile: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/vagrant/git/Cartfile, NSUnderlyingError=0x7fd792c2acb0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Running carthage command: -c carthage bootstrap --platform iOS  
|                                                                              |
+---+---------------------------------------------------------------+----------+
| [31;1mx[0m | [31;1mcarthage@2.4.0 (exit code: 1)[0m                                 | 16 sec   |
+---+---------------------------------------------------------------+----------+
| Update available: 2.4.0 -> 3.0.0                                             |
| Issue tracker: https://github.com/bitrise-steplib/steps-carthage/issues      |
| Source: https://github.com/bitrise-steplib/steps-carthage                    |
+---+---------------------------------------------------------------+----------+
```

**Comment by viktorbenei** [comment]
Are you sure that the `Cartfile` is in the **root** of the repository?
From your other configs it seems it might be in the `EATMade` directory inside the repository, and not in the repository root

**Comment by heitorfr** [comment]
It's in the `EATMade` folder but that didn't change.

**Comment by viktorbenei** [comment]
Yes, but the Step did change - and you most likely upgraded to v3 of the step. Please see the release notes of 3.0.0 for a migration guide: https://github.com/bitrise-steplib/steps-carthage/releases/tag/3.0.0

**Comment by heitorfr** [comment]
I've noticed that and rolled back to 2.4.0 with the same result. The attached log uses 2.4.0

**Comment by viktorbenei** [comment]
Just updated the release note for a migration note for the workdir input (which was removed) -> use the `--project-directory ./EATMade` parameter of carthage to define the work directory

> I've noticed that and rolled back to 2.4.0 with the same result. The attached log uses 2.4.0

Yes, but as you upgraded to 3.0.0 and saved it, the unused/removed inputs were removed from your config too

**Comment by heitorfr** [comment]
Got it! Didn't notice that. Thanks

**Comment by viktorbenei** [comment]
Yeah, it wasn't included in the original release notes' migration guide - just added it to it. Sorry for the inconvenience!
