### ISSUE TITLE
Could not find com.android.support:support-annotations:25.0.1

### ISSUE THREAD

**Issue by awscherb** [bitrise-io/build.issues#6]
# Bitrise Build Issue Report template

## Description of the issue

All Android builds failing with message `Could not find com.android.support:support-annotations:25.0.1`

## Environment:

Where did the issue happen?

- Bitrise.io, Android & Docker, on Ubuntu 16.04

Which build Step causes the issue and which version of the step?
- gradle-runner@1.5.2 

## Reproducibility

- Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build) - **No**
- Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can **delete all the caches** on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches).
- If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)
- Does upgrading the build Step to the latest version help?
- When did the issue start? - **When I updated support libs to 25.0.1**

### Linux/Android stack builds

- Can it be reproduced by running the build locally with Docker (using the same docker images we use on bitrise.io), after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC) and running the build from there? (Related guide: http://blog.bitrise.io/2016/08/08/debug-your-android-linux-builds-locally-with-docker.html )

### Other stacks

- Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC) and running the build from there with the CLI?

## Build log

```
A problem occurred configuring project ':android-components'.
> A problem occurred configuring project ':android-core'.
   > Could not resolve all dependencies for configuration ':android-core:_debugCompile'.
      > Could not find com.android.support:support-annotations:25.0.1.
        Searched in the following locations:
            https://jcenter.bintray.com/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.pom
            https://jcenter.bintray.com/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.jar
            https://maven.fabric.io/public/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.pom
            https://maven.fabric.io/public/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.jar
            http://tablelist.bintray.com/maven/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.pom
            http://tablelist.bintray.com/maven/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.jar
            file:/opt/android-sdk-linux/extras/android/m2repository/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.pom
            file:/opt/android-sdk-linux/extras/android/m2repository/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.jar
            file:/opt/android-sdk-linux/extras/google/m2repository/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.pom
            file:/opt/android-sdk-linux/extras/google/m2repository/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.jar
        Required by:
            com.tablelistapp:android-core:1.9.2-at45
      > Could not find com.android.support:support-annotations:25.0.1.
        Searched in the following locations:
            https://jcenter.bintray.com/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.pom
            https://jcenter.bintray.com/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.jar
            https://maven.fabric.io/public/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.pom
            https://maven.fabric.io/public/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.jar
            http://tablelist.bintray.com/maven/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.pom
            http://tablelist.bintray.com/maven/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.jar
            file:/opt/android-sdk-linux/extras/android/m2repository/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.pom
            file:/opt/android-sdk-linux/extras/android/m2repository/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.jar
            file:/opt/android-sdk-linux/extras/google/m2repository/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.pom
            file:/opt/android-sdk-linux/extras/google/m2repository/com/android/support/support-annotations/25.0.1/support-annotations-25.0.1.jar
        Required by:
            com.tablelistapp:android-core:1.9.2-at45 > com.f2prateek.rx.preferences:rx-preferences:1.0.0
            com.tablelistapp:android-core:1.9.2-at45 > com.squareup.sqlbrite:sqlbrite:0.4.0
````

**Comment by viktorbenei** [comment]
Most likely this is due to outdated Android Support Library version - your app requires a newer ones than the one preinstalled.

Support Library is updated every weekend on the Android/Linux stack - if you have to update it in the meantime, you can do it with a `Script` step for example - see: https://bitrise-io.github.io/devcenter/android/frequent-android-issues/#could-not-find-an-android-package-or-you-have-not-accepted-the-license-agreements

**Comment by viktorbenei** [comment]
I'll close this issue, but feel free to comment if the suggested solution would not work!

**Comment by awscherb** [comment]
Yep - thanks! 👍
