### ISSUE TITLE
Issue with input: GradleFile not exist at: build.gradle

### ISSUE THREAD

**Issue by stoyicker** [bitrise-io/build.issues#7]
## Description of the issue

Issue with input: GradleFile not exist at: build.gradle. During setup, I was asked for the path to my "Gradle file", which is not descriptive at all and it didn't say either from where the path would be resolved. My best guess was the top-level build.gradle.

## Environment:

**Where did the issue happen?**

- Bitrise.io, Android stack.

**Which build Step causes the issue and which version of the step?**

(4) gradle-runner@1.5.2

## Reproducibility

- **Does a "Rebuild" help?** No.
- **Does upgrading the build Step to the latest version help?** I don't know what this means.
- **When did the issue start?** First run, 19/11/2016.

## Build log

[bcaf22590e97051e.txt](https://github.com/bitrise-io/build.issues/files/601996/bcaf22590e97051e.txt)

**Comment by viktorbenei** [comment]
Thanks for the report!

Are you sure that your `build.gradle` file is in the __root__ of your repository? Can it be that it's in a sub directory of the repository?

**Comment by viktorbenei** [comment]
> During setup, I was asked for the path to my "Gradle file"

Didn't the automatic scanner provided scanned paths for you? Was there an error in the scanner's log, or was the scan successful?

**Comment by stoyicker** [comment]
It didn't pre-fill any of the three boxes about Gradle things (this one, tasks and some other one I don't remember). I didn't see any error during setup so I'm assuming the scanner went alright.

**Comment by viktorbenei** [comment]
Are you sure that your build.gradle file is in the root of your repository? Can it be that it's in a sub directory of the repository?

**Comment by stoyicker** [comment]
My bad, it is there in disk but just realized I didn't push it yet.

**Comment by viktorbenei** [comment]
I'd suggest you to register the app again on Bitrise.io after you made it sure that the Gradle file is in the repository, that way the automatic scanner will be able to auto configure the project for you.

**Comment by EthanAI** [comment]
What should you do if build.gradle is not in the root folder? I'm dealing with a monolithic repo with multiple apps and it's taking a lot of blind guessing to make it work.

**Comment by viktorbenei** [comment]
@EthanAI if you use our Gradle Runner step then you can set the location of the build.gradle file; if you want to use multiple steps with different build.gradle files you can simply add multiple Gradle Runner steps.

**Comment by PaulWoitaschek** [comment]
Apparently you set a `GradleFile`. When I run my wrapper, I don't need to specify a gradle file, I just call
`./gradlew myTask`. 
Your  step however explicitly uses the `build.gradle` file. Why is that so?
In my case it fails because I'm using kotlin and can fix it manually by using `build.gradle.kts`. 
I think this step should rather not specify a file as the default. @viktorbenei

**Comment by godrei** [comment]
Hi @PaulWoitaschek ,
what do you mean by: 

`Your step however explicitly uses the build.gradle file.`

The step does not defined `build.gradle` as the default value for the `Optional path to the gradle build file to use` input: https://github.com/bitrise-io/steps-gradle-runner/blob/master/step.yml#L32

It is an optional input and it allows you to define which gradle file contains the task you want to run.
