### ISSUE TITLE
No applicable devices found when Exporting Archive

### ISSUE THREAD

**Issue by Streebor** [bitrise-io/build.issues#8]
My ios archive successfuly, but when it start exporting the archive if fails with an error no applicable devices found.

Exporting ipa from the archive...

Using export options
Generating export options
auto-detect export method, based on embedded profile
detected export method: development
generated export options content:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>compileBitcode</key>
		<false></false>
		<key>method</key>
		<string>development</string>
	</dict>
</plist> <nil>

[09:17:35] set -o pipefail && xcodebuild "-exportArchive" "-archivePath" "/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/__archive__075146407/WeMesh.xcarchive" "-exportPath" "/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/__export__128488410" "-exportOptionsPlist" "/Users/vagrant/deploy/export_options.plist" | xcpretty

❌  error: exportArchive: No applicable devices found.

If you can't find the reason of the error in the log, please check the raw-xcodebuild-output.log
The log file is stored in \$BITRISE_DEPLOY_DIR, and its full path
is available in the \$BITRISE_XCODE_RAW_RESULT_TEXT_PATH environment variable
Export failed, error: %!s(<nil>)
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Xcode: Create Archive (exit code: 1)                          | 27.5 min |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-new-xcode-archive/issues  |
| Source: https://github.com/bitrise-io/steps-new-xcode-archive                |
+---+---------------------------------------------------------------+----------+

## Environment:

Bitrise stack: Xcode 8.1 macOS SIerra

## Reproducibility

I can reporduce it every time. Even if I try rebuilding it fails.

Build log attached.

**Comment by viktorbenei** [comment]
Thanks for reporting, we'll respond ASAP!

**Comment by Streebor** [comment]
It worked! I have found a solution on one of your prev post.

**Comment by viktorbenei** [comment]
Which one @Streebor ? Might help others in the future.

**Comment by Streebor** [comment]
https://github.com/bitrise-io/steps-xcode-archive/issues/37#issuecomment-228091920

**Comment by Streebor** [comment]
#https://github.com/bitrise-io/steps-xcode-archive/issues/37#issuecomment-228091920

**Comment by viktorbenei** [comment]
Thanks!
