### ISSUE TITLE
error: exportArchive: The operation couldn’t be completed. (IDEDistributionErrorDomain error 3.)

### ISSUE THREAD

**Issue by StrAbZ** [bitrise-io/build.issues#9]
# Bitrise Build Issue Report template

## Description of the issue

Configured everything for an app-store release build (I first struggled with the certificate an provisioning profile, I was forgetting the wildcard one). Once I finally was able to build, I got an error when exporting the ipa from the archive.

## Environment:

It happens on the **Xcode 8.0.x, on OS X 10.11 (El Capitan)** stack during the **xcode-archive** step.
The step is at the current last version: **2.0.1**

## Reproducibility

I was never able to build a release/app-store build, this was the first time I tried and configured it. So for me the issue started once I succeed building and archiving the project.
Right now, I just need to start a new build, or hit the "Rebuild" button, to have the error.

## Build log

Relevant parts:

```
+------------------------------------------------------------------------------+
| (6) xcode-archive@2.0.1                                                      |
+------------------------------------------------------------------------------+
| id: xcode-archive                                                            |
| version: 2.0.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2016-11-18T09:19:02-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
[34mINFO[0m[09:19:02]  * [32;1m[OK][0m Step dependency (xcode) installed, available. 
[34mINFO[0m[09:19:02]  * [32;1m[OK][0m Step dependency (go) installed, available. 

[34;1mipa export configs:[0m
- ExportMethod: app-store
- UploadBitcode: yes
- CompileBitcode: yes
- TeamID: 
- UseDeprecatedExport: no
- ForceTeamID: 
- ForceProvisioningProfileSpecifier: 
- ForceProvisioningProfile: 
- ForceCodeSignIdentity: 
- CustomExportOptionsPlistContent:

...

[34;1mstep determined configs:[0m
- xcodebuildVersion: 8.0.0 (8A218a)
- xcprettyVersion: 0.2.2
- projectAction: -workspace

...

▸ Archive Succeeded

[34;1mExporting ipa from the archive...[0m

Using export options
Generating export options
using export-method input: app-store
generated export options content:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>method</key>
		<string>app-store</string>
	</dict>
</plist> <nil>

[09:27:39] [32;1mset -o pipefail && xcodebuild "-exportArchive" "-archivePath" "/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/__archive__339792222/REDACTED.xcarchive" "-exportPath" "/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/__export__303920421" "-exportOptionsPlist" "/Users/vagrant/deploy/export_options.plist" | xcpretty[0m


❌  error: exportArchive: The operation couldn’t be completed. (IDEDistributionErrorDomain error 3.)


[33;1mIf you can't find the reason of the error in the log, please check the raw-xcodebuild-output.log
The log file is stored in \$BITRISE_DEPLOY_DIR, and its full path
is available in the \$BITRISE_XCODE_RAW_RESULT_TEXT_PATH environment variable[0m
[31;1mExport failed, error: %!s(<nil>)[0m

...

+------------------------------------------------------------------------------+
|                               bitrise summary                                |
+---+---------------------------------------------------------------+----------+
|   | title                                                         | time (s) |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mactivate-ssh-key@3.1.1[0m                                        | 2.12 sec |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mgit-clone@3.4.1[0m                                               | 8.61 sec |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mcertificate-and-profile-installer@1.8.1[0m                       | 5.80 sec |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mcocoapods-install@1.5.7[0m                                       | 106 sec  |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mBuild number[0m                                                  | 2.72 sec |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mset-xcode-build-number@1.0.4[0m                                  | 2.71 sec |
+---+---------------------------------------------------------------+----------+
| [31;1mx[0m | [31;1mxcode-archive@2.0.1 (exit code: 1)[0m                            | 523 sec  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-new-xcode-archive/issues  |
| Source: https://github.com/bitrise-io/steps-new-xcode-archive                |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mslack@2.3.0[0m                                                   | 4.67 sec |
+---+---------------------------------------------------------------+----------+
| [34;1m-[0m | [34;1mdeploy-to-itunesconnect-deliver@2.6.2[0m                         | 1.32 sec |
+---+---------------------------------------------------------------+----------+
| Total runtime: 11.0 min                                                      |
+------------------------------------------------------------------------------+
```

**Comment by viktorbenei** [comment]
Can you please add the `Deploy to Bitrise.io` step to your workflow, e.g. right before the `deploy-to-itunesconnect-deliver` step?

That will attach additional debug log files to the build, like the `raw-xcodebuild-output.log` one which is mentioned in the build log.

Once you add the step, run a new build and attach / send us these debug log files (will be in the Apps & Artifacts section of the build page)

**Comment by StrAbZ** [comment]
Here are the Xcodebuild output log
[raw-xcodebuild-output.log.zip](https://github.com/bitrise-io/build.issues/files/606252/raw-xcodebuild-output.log.zip)

**Comment by viktorbenei** [comment]
The relevant parts of the log:

```
"Error Domain=IDECodesignResolverErrorDomain Code=2 \"No matching provisioning profiles found\" UserInfo={NSLocalizedRecoverySuggestion=No provisioning profiles matching an applicable signing identity were found., NSLocalizedDescription=No matching provisioning profiles found, IDECodesignResolverError_ResolutionInputsKey=<IDECodesignResolutionInputs: 0x7f9ceaa67930; portalTeamID='REDACTED', usingTeamBasedSigning='NO', bundleIdentifier='REDACTED', targetName='(null)', provisioningProfilePurpose='1', requiresProvisioningProfile='YES', provisioningProfilePlatform='iOS', certificateKind='1.2.840.113635.100.6.1.4', requiredEntitlements='{\n    \"aps-environment\" = development;\n    \"beta-reports-active\" = 1;\n    \"keychain-access-groups\" =     (\n        \"REDACTED.REDACTED\"\n    );\n}', requiredCodesignableDevices='(null)', requiredFeatures='(null)'>\n}"
```

The most frequent cause of this issue are:

1. you did not upload the provisioning profile (from the logs it seems you did)
1. the provisioning profile is outdated - please download _the latest_ version from Apple Developer Portal, and upload that to bitrise.io
1. you missed to enable a required entitlement in the distribution provisioning profile - you can enable entitlements on the Apple Developer Portal, and once updated, download the prov profile and upload it to bitrise.io

**Comment by viktorbenei** [comment]
Also, did you use [codesigndoc](https://github.com/bitrise-tools/codesigndoc) to export the files? If you did, please make sure that you can export a fully signed IPA from Xcode.app first, and run `codesigndoc` after that, as Xcode.app might update the local prov profiles during the export process, if required.

**Comment by StrAbZ** [comment]
Ok, so:

1. I have uploaded the provisioning profile
2. This is the last one, It was generated by Xcode (I don't have any to download from the Apple Developer Portal)
3. I've checked again, all my entitlements are enabled on my distribution provisioning profile

Also I've checked, the file uploaded on bitrise are the same the codesigndoc tool provided me. Except for the wildcard one, I had to export the certificate myself.

I can confirme I can export a fully signed IPA from Xcode since I finally uploaded my binary to Apple via Xcode, since I wasn't able to export from Bitrise

**Comment by viktorbenei** [comment]
Can you please try to:

1. delete all signing files from bitrise.io
1. then run codesigndoc again
1. upload the files it generates (all the files) to bitrise.io
1. and run a new build

**Comment by StrAbZ** [comment]
Ok, but what do I do for the wildcard ? because codesigndoc doesn't export it.

**Comment by viktorbenei** [comment]
Can you upload that manually - but can you please create an issue on codesigndoc's github (https://github.com/bitrise-tools/codesigndoc) with the log it generates? It should definitely pick up the file, unless your Xcode project settings specify another code signing file.

Actually, it could be even better if you could first do a clean git clone, into a new directory on your mac, and run codesigndoc there - that way you can be certain that the Xcode project config is the same as what bitrise will get, and there are no uncommitted changes / gitignored files

**Comment by StrAbZ** [comment]
Ok, it worked...

I've checked the file again, it seems the only difference was the missing provisioning profile generated by Xcode for distribution, the one labeled: "XC iOS: app.bundle.id".

Seems to work fine now.

Thank you!

**Comment by viktorbenei** [comment]
Indeed, a single `.p12` can include multiple Identities, so for simplicity `codesigndoc` exports all in a single `.p12`.

Just to be sure: so, you didn't have to do anything else, just run `codesigndoc` and upload all the files it exported, right?

**Comment by StrAbZ** [comment]
Yes.

The first time I didn't uploaded the "XC iOS" provisioning profile, thinking it was just here because it was matching the bundle id and also was on my computer. But this time I uploaded everything (include this one) and everything worked.

**Comment by viktorbenei** [comment]
Got it, thank you for the info @StrAbZ , and Happy Building! :)
